### ISSUE TITLE
Fix Readme for responsive challenge3 and challenge4

### ISSUE THREAD

**Issue by mohitkh7** [mohitkh7/devchallenges-solution#1]
Few of the challenges readme files are still template files. Update them with custom content.

**Subtasks**:

- [x] Fix readme of responsive challenge3 interior consultant.
- [x] Fix readme of responsive challenge4 recipe page
- [x] Validate URLs of other readme. Fix them if any issue is found.
- [x] Complete common readme for repo.
